--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/zachary/.config/wpg/wallpapers/nature_mountain_eagle_fog_landscape.jpg"

-- Special
background="#3c3c3c"
foreground="#fbffff"
cursor="#fbffff"

-- Colors
color0="#3c3c3c"
color1="#B9CAC8"
color2="#92AAAC"
color3="#B2C2BE"
color4="#74939A"
color5="#9DB1B1"
color6="#9FC1C8"
color7="#dce2e0"
color8="#282828"
color9="#d7ffff"
color10="#a9eef4"
color11="#cfffff"
color12="#85cad9"
color13="#b6fbfb"
color14="#b7ffff"
color15="#fbffff"
