# Shell variables
# Generated by 'wal'
wallpaper='/home/zachary/.config/wpg/wallpapers/nature_mountain_eagle_fog_landscape.jpg'

# Special
background='#3c3c3c'
foreground='#fbffff'
cursor='#fbffff'

# Colors
color0='#3c3c3c'
color1='#B9CAC8'
color2='#92AAAC'
color3='#B2C2BE'
color4='#74939A'
color5='#9DB1B1'
color6='#9FC1C8'
color7='#dce2e0'
color8='#282828'
color9='#d7ffff'
color10='#a9eef4'
color11='#cfffff'
color12='#85cad9'
color13='#b6fbfb'
color14='#b7ffff'
color15='#fbffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
